rvm:
  - 2.0.0

script:
  - "cp config/channel.constants.sample.yml config/channel.constants.yml"
  - "cp config/advanced.constants.sample.yml config/advanced.constants.yml"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rake db:test:prepare"
  - "bundle exec rake settings:update_defaults RAILS_ENV=test"
  - "bundle exec rspec"
