# All Nembrot settings go here except for secret strings

defaults: &defaults
  version: '0.9'
  locale: 'en'
  admin:
    name: Joe
    email: joe@joegatt.net
  monitoring:
    name: Joe
    email: joe@joegatt.net
  mailer:
    address: smtp.gmail.com
    port: 587
    domain: mail.joegatt.net
  evernote:
    server: https://sandbox.evernote.com
    notebooks: f63f25b7-0c4f-4541-afb3-7286d72e452b
    instructions:
      required: ['__PUBLISH']
      ignore: ['__IGNORE', '__HOLD']
  lang:
    rtl_langs: ['ar', 'fa']
  home:
    instructions:
      required: ['__HOME']
  notes:
    title_length: 40
    blurb_length: 150
    allowed_html_tags: ['a', 'blockquote', 'del', 'ins', 'li', 'ol', 'ul', 'img', 'strong']
    allowed_html_attributes: ['href', 'src', 'alt']
    sync_retries: 3
  tags:
    index:
      style: false
  sections:
    tags: ['A Typology of Philistinism', 'Nimrod', 'Wutz']
    enface: [['Wutz', 'de', 'en'], ['Wutz RC1', 'de', 'en']]
  styling:
    css_for_instructions: ['__FX_POL']
    line_height: 30
    images:
      name_length: 30
      snap: 1
      gravity: 0
      effects: tri
      standard:
        width: 780
        aspect:
          x: 16
          y: 9
      cinema:
        width: 980
        aspect:
          x: 27
          y: 10
      thumbnail:
        width: 330
      expanded:
        width: 1400
development:
  <<: *defaults
  host: localhost:3000

test:
  <<: *defaults
  host: rspec-tests

staging:
  <<: *defaults
  host: staging.joegatt.net

production:
  <<: *defaults
  host: joegatt.net
  evernote:
    server: https://www.evernote.com
    notebooks: 85d8c66d-f0ee-4c56-acac-e30ab88ce0ce
    instructions:
      required: ['__PUBLISH']
      ignore: ['__IGNORE', '__HOLD']

