# All Nembrot settings go here except for secret strings

defaults: &defaults
  version: '0.9'
  admin:
    name: Joe
    email: joe@joegatt.net
  monitoring:
    name: Joe
    email: joe@joegatt.net
  mailer:
    address: smtp.gmail.com
    port: 587
    domain: mail.joegatt.net
  evernote:
    server: https://sandbox.evernote.com
    notebooks: f63f25b7-0c4f-4541-afb3-7286d72e452b
    instructions:
      required: __PUBLISH
      ignore: __IGNORE __HOLD
  notes:
    title_length: 8
    blurb_length: 30
    allowed_html_tags: a blockquote del ins li ol ul img src alt
    allowed_html_attributes: href
    sync_retries: 3
  tags:
    cloud: true
  sections:
    tags: ["A Typology of Philistinism", "Nimrod"]

development:
  <<: *defaults
  host: localhost:3000

test:
  <<: *defaults
  host: rspec-tests

staging:
  <<: *defaults
  host: staging.joegatt.net

production:
  <<: *defaults
  host: joegatt.net
