# All Nembrot settings go here except for secret strings

defaults: &defaults
  evernote:
    user_store_url: https://sandbox.evernote.com/edam/user
    note_store_url: http://sandbox.evernote.com/edam/note
    notebook: joegattdev's notebook
  notes:
    title_length: 8
    blurb_length: 30

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
