defaults: &defaults
  database_encryption_key: dshfkgsdahkfgsdhfgasdkjfh88*YXXXX8929jjkd--sadjajkYBT^R"%
  secret_key_base: djhgiemvhimiryfcsjoweiqw98378ty9276vhshxbzkspqoewkfflregigjweiuweu923r72380190384957583785ytuhdgjhknvjsksklaskdqpwoeioqeriowetwirutieruti
  mailer:
    user_name: admin@joegatt.net
    password: flAhhar09
  auth:
    evernote:
      consumer_key: joegatt-6398
      consumer_secret: 1283f7bfdf033e9f
    detect_language:
      api_key: 2252f8eaada2a0eb9d2bdce5e8cf234c
    world_cat:
      api_key: wRXF1DxPbZ0PLsadbac5BmNSoZWI6MvB5Kx6jXfp2PGSB6DlJSRLzNB9GJkCjNOnLR4zuvjIgxnXmOAy
    isbndb:
      api_key: 1A4S438C

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
