defaults: &defaults
  database_encryption_key: CHANGEME
  mailer:
    user_name: CHANGEME
    password: CHANGEME
  auth:
    evernote:
      consumer_key: CHANGEME
      consumer_secret: CHANGEME

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
